name: PrimeFactions
version: '${project.version}'
main: net.primegames.primefactions.PrimeFactions
api-version: 1.18
load: POSTWORLD
depend:
  - LuckPerms
  - floodgate
  - Geyser-Spigot
  - Vault
  - Essentials
  - HolographicDisplays